# Configurações do Servidor
server.port=8080

# Configurações de Conexão com o PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/delivery_app
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD:123321}

# O Hibernate vai criar as tabelas do banco de dados automaticamente
spring.jpa.hibernate.ddl-auto=update

# Configurações do JWT
jwt.secret=${JWT_SECRET:c5385a92868b00466acef3ae7ba63e82e990cb04b5de8a110f87c64ca0aeb036}
jwt.expiration=86400000